---
title: "timing_comp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
```

### right censor survival analysis
```{r}
censormodel <- "model{
for(i in 1:n){
is.censor[i] ~ dinterval(Z[i],t.cen[i])
Z[i] ~ dlnorm(mu[i], inv_var)
 mu[i] <- (beta0+x1[i]*b01+x2[i]*b02)+(beta1+x1[i]*b11+x2[i]*b12)*log(W[i])

}
beta0~dnorm(0,0.001)

beta1~dnorm(0,0.001)

b01~dnorm(0,0.001)

b11~dnorm(0,0.001)

b02~dnorm(0,0.001)

b12~dnorm(0,0.001)

inv_var ~ dgamma(0.01, 0.01)

}

"

```

### priors on log_w
```{r}
censormodel_var <- "model{
for(i in 1:n){
is.censor[i] ~ dinterval(Z[i],t.cen[i])
Z[i] ~ dlnorm(mu[i], inv_var)
 mu[i] <- (beta0+x1[i]*b01+x2[i]*b02)+(beta1+x1[i]*b11+x2[i]*b12)*log_W[i]
 
 log_W[i]~ dnorm(mean_lnW[i],inv_var_w[i])

}
beta0~dnorm(0,0.001)

beta1~dnorm(0,0.001)

b01~dnorm(0,0.001)

b11~dnorm(0,0.001)

b02~dnorm(0,0.001)

b12~dnorm(0,0.001)

inv_var ~ dgamma(0.01, 0.01)

}

"

```

```{r}
popden <- read.csv("D:/re-emergent RSV timing/population-density-2021.csv",header = T)
Z <- onset.2020.FL
t.cen <- max(onset.2020$onset)-onset.2020$onset[onset.2020$state=='FL']
n <- length(Z)
t.cen <- rep(t.cen,n)

x1 <- as.numeric(popden$Population.Density.2020.Census)
x1[30] <- 1263
x1[39] <- 1061.4
x1 <- scale(x1)
x2 <- as.numeric(popden$familysize)
x2 <- scale(x2)
is.censor <- ifelse(is.na(Z),1,0)

data <- list(n=n-1,Z=Z[-9],t.cen=t.cen[-9],is.censor=is.censor[-9],W=onset.whole.FL[-9],x1=as.numeric(x1)[-9],x2=as.numeric(x2)[-9],mean_lnW=lnW_FL_mean[-9],inv_var_w=lnW_FL_inv_var[-9])
tinits1 <- 1+onset.2020$onset
is.na(tinits1) <- complete.cases(onset.2020$grey)
tinits2 <- tinits1+1
censorinit <- list(list(Z=tinits1),list(Z=tinits2))
```

```{r}
censor <- jags.model(textConnection(censormodel_var),data=data,n.chains = 2)

update(censor,100000)

censorsample <- coda.samples(censor,c("beta0","beta1","b01","b02","b11","b12"),500000,thin=10)
```
```{r}
#par(ask=T)
traceplot(censorsample)
summary(censorsample)
densplot(censorsample)
```

```{r}
post <- as.data.frame(as.matrix(censorsample))
b12 <- post[,"b12"]
beta1 <- post[,"beta1"]
plot(b12*x2[1]+beta1,type="l")
plot(b12*x2[2]+beta1,type="l")
```

### right censor sensitivity analysis
```{r}
censormodel_sim <- "model{
for(i in 1:n){
is.censor[i] ~ dinterval(Z[i],t.cen[i])
Z[i] ~ dlnorm(mu[i], inv_var)
 mu[i] <- (beta0)+(beta1)*log(W[i])

}
beta0~dnorm(0,0.001)

beta1~dnorm(0,0.001)

inv_var ~ dgamma(0.01, 0.01)

}

"

```


