---
title: "rsv_covid"
author: "Dan Weinberger"
date: "2/18/2020"
output: html_document
---

```{r setup, include=FALSE}
#rmarkdown::render('rsv_covid.Rmd', output_file = 'docs/index.html')
knitr::opts_chunk$set(echo = F)
#install.packages('curl')
#library(curl)
#if (!require("devtools")) install.packages("devtools")
#devtools::install_github("PMassicotte/gtrendsR", force=TRUE)
library(RApiDatetime)
library(gtrendsR)
library(pbapply)
library(reshape2)
library(MMWRweek)
```
In these plots, we pulled searches for 'RSV' from Google trends using the gtrendsR package. Previous work found that Google searches for 'RSV' capture spatiotemporal variations in RSV activity across the US: https://www.biorxiv.org/content/10.1101/607119v1


```{r, eval=F}

state.abb.us <- paste0('US-', state.abb)
#searches <- c("flu",'pneumonia','fever','rsv', 'bronchiolitis')
searches <- c('rsv', 'bronchiolitis')


state.trends <- pblapply(state.abb.us, function(x) {
    lapply(searches, function(y){
        gtrends(keyword=y, geo = c(x), category = 0, gprop='web')
    })
  }
)


saveRDS(state.trends, 'all.state.data.rds')
```

```{r, eval=F}
#Other geographies
#
#data("countries")
#View(countries)
test.grps <- list( c( 'RSV','ZA' ), 
                  c('bronquiolitis', 'AR'), 
                  c('bronquiolite','BR'),
                  c('bronchiolite','FR'),

                  c('bronchiolite','FR-J')
      )
names(test.grps) <- c('S. Africa','Argentina', 'Brazil','France', 'France-Paris region')

country.trends <- lapply(test.grps, function(x) gtrends(keyword=x[1], geo = x[2], category = 0, gprop='web'))

saveRDS(country.trends, 'country.data.rds')

```


```{r}
l1a <- readRDS('all.state.data.rds')
#l1 <- c(l1a, l1b)
l2 <- lapply(l1a,function(x) lapply(x, '[[','interest_over_time'))
l3 <- lapply(l2, function(x) do.call( 'rbind.data.frame', x))

d1 <- do.call( 'rbind.data.frame', l3)

d1.m <- melt(d1[,c('date','hits','geo', 'keyword')], id.vars=c('geo','date','keyword'))

d1.m$value <- as.numeric(d1.m$value)
#hist(d1.m$value[d1.m$geo=='US-FL'])
d1.c <- acast(d1.m ,date~geo~keyword)


#Case by weekN and year
d1.m.alt <- d1.m
dates2 <- MMWRweek(as.Date(d1.m$date))
d1.m.alt <- cbind.data.frame(d1.m.alt,dates2[,c('MMWRyear', 'MMWRweek')])
d1.m.alt$epiyr <- d1.m.alt$MMWRyear
d1.m.alt$epiyr[d1.m.alt$MMWRweek<=26] <- d1.m.alt$MMWRyear[d1.m.alt$MMWRweek<=26] - 1
d1.m.alt$epiwk <- d1.m.alt$MMWRweek
d1.m.alt$epiwk[d1.m.alt$MMWRweek<=26] <- d1.m.alt$MMWRweek[d1.m.alt$MMWRweek<=26] + 52

d1.c.alt <- acast(d1.m.alt ,epiyr~epiwk~geo~keyword, fun.aggregate = sum)

last.wk <- max(d1.m.alt$epiwk[d1.m.alt$epiyr==2020] )
d1.c.alt['2020',dimnames(d1.c.alt)[[2]]>last.wk,,] <- NA
```

```{r, fig.width=8, fig.height=6}
cols <- c(rep('gray',5),'red')
states <- dimnames(d1.c.alt)[[3]]
par(mfrow=c(5,5), mar=c(2,2,1,0))
lapply(states, function(x){
  matplot(t(d1.c.alt[,,x,'rsv']), type='l', col=cols, bty='l', xlab='', ylab='', xlim=c(1,52), main=x, lty=1)

})

```

If we look at searches for 'bronchiolitis', the picture is a bit more mixed, with several states showing recent increases.
```{r, fig.width=8, fig.height=6}
cols <- c(rep('gray',5),'red')
states <- dimnames(d1.c.alt)[[3]]
par(mfrow=c(5,5), mar=c(2,2,1,0))

lapply(states, function(x){
  matplot(t(d1.c.alt[,,x,'bronchiolitis']), type='l', col=cols, bty='l', xlab='', ylab='', xlim=c(1,52), main=x, lty=1)

})

```
## Other Countries 
```{r}
l1b <- readRDS( 'country.data.rds')

l2 <- lapply(l1b,  '[[','interest_over_time')

d1 <- do.call( 'rbind.data.frame', l2)

d1.m <- melt(d1[,c('date','hits','geo')], id.vars=c('geo','date'))

d1.m$value <- as.numeric(d1.m$value)
#hist(d1.m$value[d1.m$geo=='US-FL'])
d1.c <- acast(d1.m ,date~geo)


#Case by weekN and year
d1.m.alt <- d1.m
dates2 <- MMWRweek(as.Date(d1.m$date))
d1.m.alt <- cbind.data.frame(d1.m.alt,dates2[,c('MMWRyear', 'MMWRweek')])
d1.m.alt$epiyr <- d1.m.alt$MMWRyear
d1.m.alt$epiyr[d1.m.alt$MMWRweek<=26] <- d1.m.alt$MMWRyear[d1.m.alt$MMWRweek<=26] - 1
d1.m.alt$epiwk <- d1.m.alt$MMWRweek
d1.m.alt$epiwk[d1.m.alt$MMWRweek<=26] <- d1.m.alt$MMWRweek[d1.m.alt$MMWRweek<=26] + 52

d1.c.alt <- acast(d1.m.alt ,epiyr~epiwk~geo, fun.aggregate = sum)

last.wk <- max(d1.m.alt$epiwk[d1.m.alt$epiyr==2020] )
d1.c.alt['2020',dimnames(d1.c.alt)[[2]]>last.wk,] <- NA

countries <- c('FR','FR-J')

cols <- c(rep('gray',5),'red')
states <- dimnames(d1.c.alt)[[3]]
par(mfrow=c(1,1), mar=c(2,2,1,0))
lapply(countries, function(x){
  matplot(t(d1.c.alt[,,x]), type='l', col=cols, bty='l', xlab='', ylab='', xlim=c(1,52), main=x, lty=1)

})
```


```{r, fig.width=4, fig.height=3}
l2 <- lapply(l1b,  '[[','interest_over_time')

d1 <- do.call( 'rbind.data.frame', l2)

d1.m <- melt(d1[,c('date','hits','geo')], id.vars=c('geo','date'))

d1.m$value <- as.numeric(d1.m$value)
#hist(d1.m$value[d1.m$geo=='US-FL'])
d1.c <- acast(d1.m ,date~geo)


#Case by weekN and year
d1.m.alt <- d1.m
dates2 <- MMWRweek(as.Date(d1.m$date))
d1.m.alt <- cbind.data.frame(d1.m.alt,dates2[,c('MMWRyear', 'MMWRweek')])


d1.c.alt <- acast(d1.m.alt ,MMWRyear~MMWRweek~geo, fun.aggregate = sum)

last.wk <- max(d1.m.alt$MMWRweek[d1.m.alt$MMWRyear==2021] )
d1.c.alt['2021',dimnames(d1.c.alt)[[2]]>last.wk,] <- NA

countries <- c( 'AR','BR','ZA')

cols <- c(rep('gray',4),'red','red')
states <- dimnames(d1.c.alt)[[3]]
par(mfrow=c(1,1), mar=c(2,2,1,0))
lapply(countries, function(x){
  matplot(t(d1.c.alt[,,x]), type='l', col=cols, bty='l', xlab='', ylab='', xlim=c(1,52), main=x, lty=1)

})

```
```

